### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by davelab6** [Tgemayel/variable-fonts-figma#1]
```
$ brew install figma

$ brew info figma
figma: 95.8.0 (auto_updates)
https://www.figma.com/
/usr/local/Caskroom/figma/95.8.0 (119B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/figma.rb
==> Name
Figma
```

<img width="1400" alt="Screen Shot 2021-03-31 at 13 42 22" src="https://user-images.githubusercontent.com/261579/113187739-34136c00-9227-11eb-8baa-c4468b616630.png">

<img width="929" alt="Screen Shot 2021-03-31 at 13 42 42" src="https://user-images.githubusercontent.com/261579/113189153-e13ab400-9228-11eb-9695-379091aba69d.png">

<img width="903" alt="Screen Shot 2021-03-31 at 13 42 51" src="https://user-images.githubusercontent.com/261579/113189185-e8fa5880-9228-11eb-8747-d7e891eda9d9.png">

<img width="1419" alt="Screen Shot 2021-03-31 at 13 43 02" src="https://user-images.githubusercontent.com/261579/113189200-ec8ddf80-9228-11eb-8214-950ceabd351a.png">

The fuzz seems to be an issue with any electron app on this machine right now, here's Notion also going crazy today. 

<img width="515" alt="Screen Shot 2021-03-31 at 13 44 54" src="https://user-images.githubusercontent.com/261579/113189275-016a7300-9229-11eb-9955-2306e18d801c.png">

**Comment by davelab6** [comment]
```
brew install yarn;
yarn;
yarn build:watch;
```

Works :)

**Comment by bghryct** [comment]
@davelab6 suggestion works for me as well. 
Bump.
