### ISSUE TITLE
Include Roboto Flex via Github CDN?

### ISSUE THREAD

**Issue by davelab6** [Tgemayel/variable-fonts-figma#11]
https://github.com/TypeNetwork/Roboto-Flex/blob/master/fonts/RobotoFlex%5Bslnt%2Cwdth%2Cwght%2Copsz%5D.ttf

This font would be great to have 'out of the box' but its under development and not in the GF API. 

Can it be included via Github's CDN URL?

**Comment by davelab6** [comment]
This might relate to #5

**Comment by Tgemayel** [comment]
Fixed :) b82303547996b4bc5c132e99d60ca13c1b22f0e6
