### ISSUE TITLE
Include a `build: yarn` line in manifest.json?

### ISSUE THREAD

**Issue by davelab6** [Tgemayel/variable-fonts-figma#14]
https://www.figma.com/plugin-docs/manifest/ says

> `build`: string
>
> Experimental! A shell command to run before we load the file specified in main and ui. This can be used to call build commands such as compiling with Typescript, running Webpack, etc. The command is run in the directory of the manifest.

I guess we could include a `build: yarn` line in the manifest for convenience?

**Comment by Tgemayel** [comment]
Fixed b82303547996b4bc5c132e99d60ca13c1b22f0e6
