### ISSUE TITLE
Remove 0.3 prerelease tag, as it doesn't run 

### ISSUE THREAD

**Issue by davelab6** [Tgemayel/variable-fonts-figma#20]
<img width="1400" alt="Screen Shot 2021-04-15 at 13 40 04" src="https://user-images.githubusercontent.com/261579/114914332-2990cf00-9df0-11eb-9128-302edec7352d.png">
<img width="800" alt="Screen Shot 2021-04-15 at 13 40 09" src="https://user-images.githubusercontent.com/261579/114914334-2a296580-9df0-11eb-9433-68b64025f6f0.png">

https://github.com/Tgemayel/variable-fonts-figma/releases/tag/v3

**Comment by tomasdev** [comment]
This happens because the manifest.json contains `dist/` prefix on ui/code. Removing the prefix so the full file looks like:
```
{
  "name": "Variable Fonts",
  "id": "00000000",
  "api": "1.0.0",
  "main": "code.js",
  "ui": "ui.html"
}
```

works as expected.
