### ISSUE TITLE
Font list went empty

### ISSUE THREAD

**Issue by davelab6** [Tgemayel/variable-fonts-figma#25]
Using the plugin from the figma store in the desktop app:

<img width="380" alt="Screen Shot 2021-04-28 at 11 52 37" src="https://user-images.githubusercontent.com/261579/116434285-4aa5e680-a818-11eb-9dfc-4df90a9928cd.png">

**Comment by davelab6** [comment]
Reproduced in the web app too

**Comment by Tgemayel** [comment]
Thanks for flagging! Fixed 721c27a4718abb49440f8cef66e4e693bf6b626a
