### ISSUE TITLE
Bug with remembering object's input string

### ISSUE THREAD

**Issue by davelab6** [Tgemayel/variable-fonts-figma#8]
In the README PR #3 I wrote,

> The plugin remembers which Vector graphic objects it created, and their text remains editable in the plugin panel.

This seems a bit buggy at the first `0.1.0` release, as it is possible to select an object and see its text revert to the default `Default Text` string. I'm not quite sure what triggers this, but it happened a few times as I was playing around - but I can't easily reproduce

**Comment by Tgemayel** [comment]
Believe this is fixed - closing for now unless it re-appears
